#ifndef OPENCYCLO_UI_ENGINE_WIDGET_TYPES_H
#define OPENCYCLO_UI_ENGINE_WIDGET_TYPES_H

#include <stdint.h>

enum WidgetType : uint8_t {
  WIDGET_NONE = 0,
  WIDGET_SPEED,
  WIDGET_AVG_SPEED,
  WIDGET_MAX_SPEED,
  WIDGET_DISTANCE,
  WIDGET_RIDE_TIME,
  WIDGET_CADENCE,
  WIDGET_HEART_RATE,
  WIDGET_POWER,
  WIDGET_ALTITUDE,
  WIDGET_GRADE,
  WIDGET_TOTAL_ASCENT,
  WIDGET_ELEVATION_CHART,
  WIDGET_CLOCK,
  WIDGET_BATTERY,
  WIDGET_GPS_DIAGNOSTICS,
  WIDGET_NMEA_CONSOLE,
  WIDGET_BLE_MANAGER,
  WIDGET_SETTINGS_LIST,
  WIDGET_TYPE_COUNT
};

struct Rect {
  int16_t x;
  int16_t y;
  int16_t w;
  int16_t h;
};

#endif // OPENCYCLO_UI_ENGINE_WIDGET_TYPES_H
